services:
  alice:
    build:
      context: ../..
      dockerfile: .devcontainer/network/Dockerfile
    environment:
      - SELF_PARTY=alice
      - ALL_PARTIES=alice,bob
    ports:
      # Jupyter
      - 8090:8888
      # Ray Dashboard
      - 8091:8265
    entrypoint: /home/vscode/scripts/start.sh
    volumes:
      - type: bind
        source: ../..
        target: /home/vscode/workspace
        consistency: cached

  bob:
    build:
      context: ../..
      dockerfile: .devcontainer/network/Dockerfile
    environment:
      - SELF_PARTY=bob
      - ALL_PARTIES=alice,bob
    ports:
      # Jupyter
      - 8092:8888
      # Ray Dashboard
      - 8093:8265
    entrypoint: /home/vscode/scripts/start.sh
    volumes:
      - type: bind
        source: ../..
        target: /home/vscode/workspace
        consistency: cached
