# generated by datamodel-codegen:
#   filename:  Trace.json
#   timestamp: 2023-10-08T09:35:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, Field
from secretnote.utils.pydantic import ProtoModel

from ...common import v1


class Event(ProtoModel):
    class Config:
        extra = Extra.allow

    time_unix_nano: Optional[str] = Field(
        None, description='time_unix_nano is the time the event occurred.'
    )
    name: Optional[str] = Field(
        None,
        description='name of the event. This field is semantically required to be set to non-empty string.',
    )
    attributes: Optional[List[v1.KeyValue]] = Field(
        None,
        description='attributes is a collection of attribute key/value pairs on the event. Attribute keys MUST be unique (it is not allowed to have more than one attribute with the same key).',
    )
    dropped_attributes_count: Optional[int] = Field(
        None,
        description='dropped_attributes_count is the number of dropped attributes. If the value is 0, then no attributes were dropped.',
    )


class Link(ProtoModel):
    class Config:
        extra = Extra.allow

    trace_id: Optional[bytes] = Field(
        None,
        description='A unique identifier of a trace that this linked span is part of. The ID is a 16-byte array.',
    )
    span_id: Optional[bytes] = Field(
        None,
        description='A unique identifier for the linked span. The ID is an 8-byte array.',
    )
    trace_state: Optional[str] = Field(
        None, description='The trace_state associated with the link.'
    )
    attributes: Optional[List[v1.KeyValue]] = Field(
        None,
        description='attributes is a collection of attribute key/value pairs on the link. Attribute keys MUST be unique (it is not allowed to have more than one attribute with the same key).',
    )
    dropped_attributes_count: Optional[int] = Field(
        None,
        description='dropped_attributes_count is the number of dropped attributes. If the value is 0, then no attributes were dropped.',
    )
    flags: Optional[int] = Field(
        None,
        description='Flags, a bit field. 8 least significant bits are the trace flags as defined in W3C Trace Context specification. Readers MUST not assume that 24 most significant bits will be zero. When creating new spans, the most-significant 24-bits MUST be zero.  To read the 8-bit W3C trace flag (use flags & SPAN_FLAGS_TRACE_FLAGS_MASK).  [Optional]. See https://www.w3.org/TR/trace-context-2/#trace-flags for the flag definitions.',
    )
