# generated by datamodel-codegen:
#   filename:  Trace.json
#   timestamp: 2023-10-08T09:35:43+00:00

from __future__ import annotations

from typing import Optional

from pydantic import Extra
from secretnote.utils.pydantic import ProtoModel

from .opentelemetry.proto.trace import v1


class Model(ProtoModel):
    __root__: Trace


class Trace(ProtoModel):
    class Config:
        extra = Extra.allow

    data: Optional[v1.TracesData] = None


Model.update_forward_refs()
Trace.update_forward_refs()
