services:
  alice:
    image: secretflow/secretnote:1.10.0b0
    pull_policy: if_not_present
    platform: linux/arm64
    environment:
      - SELF_PARTY=alice
    ports:
      - 55000:8888
    volumes:
      - ./alice:/home/secretnote/workspace

  bob:
    image: secretflow/secretnote:1.10.0b0
    pull_policy: if_not_present
    platform: linux/arm64
    environment:
      - SELF_PARTY=bob
    ports:
      - 55111:8888
    volumes:
      - ./bob:/home/secretnote/workspace
