services:
  alice:
    image: secretflow/secretnote:1.9.0b0
    pull_policy: if_not_present
    platform: linux/amd64
    environment:
      - SELF_PARTY=alice
    ports:
      - 8090:8888
    volumes:
      - ./alice:/root/workspace

  bob:
    image: secretflow/secretnote:1.9.0b0
    pull_policy: if_not_present
    platform: linux/amd64
    environment:
      - SELF_PARTY=bob
    ports:
      - 8092:8888
    volumes:
      - ./bob:/root/workspace
