services:
  alice:
    image: secretflow/secretnote:1.11.0b1
    pull_policy: if_not_present
    platform: linux/amd64
    environment:
      - SELF_PARTY=alice
    ports:
      - 8090:8888
    volumes:
      - ./alice:/home/secretnote/workspace

  bob:
    image: secretflow/secretnote:1.11.0b1
    pull_policy: if_not_present
    platform: linux/amd64
    environment:
      - SELF_PARTY=bob
    ports:
      - 8092:8888
    volumes:
      - ./bob:/home/secretnote/workspace
