# generated by datamodel-codegen:
#   filename:  Trace.json
#   timestamp: 2023-10-08T09:35:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Extra, Field
from secretnote.utils.pydantic import ProtoModel

from ..common import v1


class Resource(ProtoModel):
    class Config:
        extra = Extra.allow

    attributes: Optional[List[v1.KeyValue]] = Field(
        None,
        description='Set of attributes that describe the resource. Attribute keys MUST be unique (it is not allowed to have more than one attribute with the same key).',
    )
    dropped_attributes_count: Optional[int] = Field(
        None,
        description='dropped_attributes_count is the number of dropped attributes. If the value is 0, then no attributes were dropped.',
    )
