[project]
authors = [{name = "Tony Wu", email = "tonywu6@protonmail.com"}]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Private :: Do Not Upload",
]
dependencies = [
  "orjson>=3.9.9",
  "loguru>=0.7.2",
  "packaging>=23.1",
  "pydantic>=1.10, <2",
  "opentelemetry-api>=1.20.0",
  "opentelemetry-sdk>=1.20.0",
  "more-itertools>=10.1.0",
  "importlib-resources>=5.12",
  "networkx>=2.8.8",
  "stack_data>=0.6.3",
  "astunparse>=1.6.3",
  "tqdm>=4.66.1",
  "ipywidgets>=8.1.1",
]
description = "Notebook suite for SecretFlow"
dynamic = ["version"]
name = "secretnote"
readme = "README.md"
requires-python = ">=3.8, <3.12"

[project.scripts]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "package.json"
# regex to match "version" in package.json
pattern = '"version": "(?P<version>[^"]+)"'

[tool.hatch.build]
artifacts = ["*.js", "*.json", "*.html"]
directory = "dist"
only-include = ["src", "package.json"]

[tool.hatch.build.targets.wheel]
sources = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.extend-per-file-ignores]
"src/secretnote/proto/**/*" = ["E501", "I001"]
