[tool.poetry]
name = "secretnote"
version = "0.4.0"
description = ""
authors = ["wenyu.jqq <wenyu.jqq@antgroup.com>"]
readme = "README.md"
packages = [{include = "libro_server"}]
include = ['README.md', 'setup.py', 'jupyter-config', 'libro_server/static/**/*', 'libro_server/template', 'libro_server/*.py']

[tool.poetry.scripts]
secretnote = 'libro_server.app:launch'

[tool.poe.tasks]
dev = "secretnote --config=./dev-config/jupyter_server_config.py --debug"
publish = "twine upload dist/*"
gateway = 'jupyter lab --config=./dev-config/jupyter_server_config.py --debug --gateway-url=http://127.0.0.1:8888'

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
jupyter-server = "^2.7.0"
ipykernel = "^6.24.0"
jupyter-resource-usage = "^1.0.1"
ipython-sql = "^0.5.0"
pymysql = "^1.1.0"


[tool.poetry.group.dev.dependencies]
jupyter-lsp = "^2.2.0"
pandas = "^2.0.1"
transformers = "^4.31.0"
matplotlib = "^3.7.2"
poethepoet = "^0.21.1"
twine = "^4.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
