// Clean `node_modules`, `dist` and other folders generated by the build process.

const fs = require('fs');
const path = require('path');

const workDir = path.join(__dirname, '../');
const distAndDep = (dir) => [`${dir}/dist`, `${dir}/node_modules`];
const candidates = [
  // under workDir
  '.nx',
  '.pytest_cache',
  '.venv',
  'node_modules',
  // under legacy (mainly telemetry features related)
  ...distAndDep('./legacy/secretnote-ui'),
  ...distAndDep('./legacy/telemetry'),
  // components
  ...distAndDep('./packages/secretnote-scql'),
  ...distAndDep('./packages/secretnote-sf'),
  // playgrounds
  ...distAndDep('./packages/secretnote-scql-site'),
  ...distAndDep('./packages/secretnote-sf-site'),
  // Python projects
  './pyprojects/secretnote/.ipynb_checkpoints',
  ...distAndDep('./pyprojects/secretnote'),
  './pyprojects/secretnote/secretnote/__pycache__',
  './pyprojects/secretnote/secretnote/sf/www',
  './pyprojects/secretnote/secretnote/scql/www',
  './pyprojects/secretnote/secretnote/sf/__pycache__',
  './pyprojects/secretnote/secretnote/scql/__pycache__',
].map((v) => path.join(workDir, v));

candidates.forEach((dir) => {
  console.log(`Removing ${dir} ...`);
  fs.rmSync(dir, { recursive: true, force: true });
});

console.log('Done cleaning up.');
