# This Actions is used to hint users to sign the CLA if they have not done so yet.
name: 'GitHub: CLA Assistant'

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
jobs:
  assistant:
    uses: secretflow/.github/.github/workflows/cla.yml@main
    secrets: inherit
