# https://github.com/sveltejs/kit/blob/32afba695088b946aefe96da75b36de9b0667fbe/.github/workflows/release.yml
name: 'Release'

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: Pre-release CI
    uses: ./.github/workflows/ci.yml

    permissions:
      contents: read
      actions: read

  publish:
    needs: [ci]
    if: |
      needs.ci.result == 'success'

    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Bootstrap and Build
        shell: bash
        run: |
          pnpm run ci:bootstrap
          pnpm run ci:build

      - name: Publish
        shell: bash
        run: |
          cd pyprojects/secretnote
          pnpm publish:py
